LeaveON/Controllers/AspNetUserClaimsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Repository.Models;

namespace LeaveON.Controllers
{
  public class AspNetUserClaimsController : Controller
  {
    private LeaveONEntities db = new LeaveONEntities();

    // GET: AspNetUserClaims
    public async Task<ActionResult> Index()
    {
      ViewBag.Employees = new SelectList(db.AspNetUsers.OrderBy(x=>x.UserName), "Id", "UserName");
      //ViewBag.LeaveTypes = new SelectList(db.LeaveTypes, "Id", "Name");
      ViewBag.Departments = new SelectList(db.Departments.OrderBy(x=>x.Name), "Id", "Name");
      var aspNetUserClaims = db.AspNetUserClaims.Include(a => a.AspNetUser);
      return View(await aspNetUserClaims.ToListAsync());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Index([Bind(Include = "Id,UserId,ClaimType,ClaimValue")] AspNetUserClaim aspNetUserClaim)
    {
      if (ModelState.IsValid)
      {
        aspNetUserClaim.ClaimType = db.Departments.FirstOrDefault(x => x.Id.ToString() == aspNetUserClaim.ClaimValue).Name;
        db.AspNetUserClaims.Add(aspNetUserClaim);
        await db.SaveChangesAsync();
        return RedirectToAction("Index");
      }

      ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Hometown", aspNetUserClaim.UserId);
      return View(aspNetUserClaim);
    }
    //DeleteRight
    [HttpPost]
    [ValidateAntiForgeryToken]
    //public async Task<ActionResult> DeleteRight([Bind(Include = "Id,UserId,ClaimType,ClaimValue")] AspNetUserClaim aspNetUserClaim)
    public async Task<ActionResult> DeleteClaim(int ClaimId)
    {
      AspNetUserClaim aspNetUserClaim = await db.AspNetUserClaims.FindAsync(ClaimId);
      db.AspNetUserClaims.Remove(aspNetUserClaim);
      await db.SaveChangesAsync();
      return RedirectToAction("Index");
    }
    
    protected override void Dispose(bool disposing)
    {
      if (disposing)
      {
        db.Dispose();
      }
      base.Dispose(disposing);
    }
  }
}

LeaveON/Views/AspNetUserClaims/Index.cshtml
@model IEnumerable<Repository.Models.AspNetUserClaim>

@{
  ViewBag.Title = "Access Rights";
  Layout = "~/Views/Shared/_Layout.cshtml";
}

  <div class="form-horizontal">
    @using (Html.BeginForm("Index", "AspNetUserClaims"))
    {
      @Html.AntiForgeryToken()


      <h4>Access Rights</h4>
      <hr />
      @Html.ValidationSummary(true, "", new { @class = "text-danger" })

      @Html.DropDownList("UserId", (IEnumerable<SelectListItem>)ViewBag.Employees, null, new { @class = "form-control" })
      @Html.DropDownList("ClaimValue", (IEnumerable<SelectListItem>)ViewBag.Departments, null, new { @class = "form-control" })


      <div class="form-group">
        <div class="col-md-offset-2 col-md-10 AddClaim">
          <input type="submit" value="Add" class="btn btn-primary" />
        </div>
      </div>

    }
    
    @using (Html.BeginForm("DeleteClaim", "AspNetUserClaims"))
    {
      @Html.AntiForgeryToken()

      <table class="table">
        <tr>

          <th>
            User
          </th>
          <th>
            Department
          </th>

          <th></th>
        </tr>

        @foreach (var item in Model)
        {
          <tr>
            @*<td style="display:none;"><input type="hidden" name="AnnualOffDay.Index" value="@(counter)" /></td>*@
            @*<td>
              @Html.HiddenFor(modelItem => item.UserId)
            </td>*@
            <td>
              @Html.DisplayFor(modelItem => item.AspNetUser.UserName)
            </td>
            <td>
              @Html.DisplayFor(modelItem => item.ClaimType)
            </td>

            <td>
              @*@Html.ActionLink("Delete", "Delete", new { id = item.Id })*@
              @*<input type="submit" Class="DeleteClaim" name="AspNetUserClaim.ClaimType" id="Delete@(item.Id)" value="Delete@(item.Id)" class="btn btn-danger" />*@
              

              <div class="form-group">
              <div class="col-md-offset-2 col-md-10">
                    @*<input type="submit" value="Add" class="btn btn-primary" />*@
                <button type="submit" Class="btn btn-danger DeleteClaim" name="ClaimId" id="Delete@(item.Id)" value="@(item.Id)">Delete</button>
              </div>
              </div>

            </td>
          </tr>
        }

      </table>
    }

  </div>

<script>
  $(".DeleteClaim").on('click', function () {
    if (!confirm('Are you sure?')) {
      return false;
    }
  });
    //
  $(".AddClaim").on('click', function () {
    if (!confirm('Are you sure?')) {
      return false;
    }
  });
</script>