LeaveON/Controllers/AccessTimeDataController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TimeManagement.Models;
using Repository.Models;
using Microsoft.AspNet.Identity;
using System.Security.Claims;

namespace LeaveON.Controllers
{
  public class AccessTimeDataController : Controller
  {
    private BioStarEntities dbBioStar = new BioStarEntities();
    LeaveONEntities dbLeaveOn = new LeaveONEntities();
    // GET: AccessTimeData
    public async Task<ActionResult> PersonalData(string ReqMonthYear)
    {
      //DateTime myDate = DateTime.ParseExact("2009-05-08 14:40:52,531", "yyyy-MM-dd HH:mm:ss,fff",
      //                                 System.Globalization.CultureInfo.InvariantCulture);
      DateTime reqDate = DateTime.Now;
      if (!string.IsNullOrEmpty(ReqMonthYear))
      {
        reqDate = DateTime.ParseExact(ReqMonthYear, "MM-yyyy",
                                 System.Globalization.CultureInfo.CurrentCulture);
      }
      reqDate = reqDate.AddYears(-1);
      string userId = User.Identity.GetUserId();
      int bioStarEmpNum = dbLeaveOn.AspNetUsers.FirstOrDefault(x => x.Id == userId).BioStarEmpNum.Value;

      IQueryable<UD_TB_AccessTime_Data> topRows = dbBioStar.UD_TB_AccessTime_Data.Where(x => x.EmployeeNumber == bioStarEmpNum && ((x.Date_IN.Value.Month == reqDate.Month && x.Date_IN.Value.Year == reqDate.Year) ||
                                                                                 x.Date_OUT.Value.Month == reqDate.Month && x.Date_OUT.Value.Year == reqDate.Year)).AsQueryable<UD_TB_AccessTime_Data>();
      List<UD_TB_AccessTime_Data> LsttopRows = topRows.ToList<UD_TB_AccessTime_Data>();
      //return View(await db.UD_TB_AccessTime_Data.ToListAsync());
      if (string.IsNullOrEmpty(ReqMonthYear))
      {
        return View(await topRows.ToListAsync());
      }
      else
      {
        return PartialView("_PersonalData", await topRows.OrderBy(i => i.Date_IN).ToListAsync());
      }

    }

    public async Task<ActionResult> DepartmentData(string ReqMonthYear, string DepartmentId)
    {



      //DateTime myDate = DateTime.ParseExact("2009-05-08 14:40:52,531", "yyyy-MM-dd HH:mm:ss,fff",
      //                                 System.Globalization.CultureInfo.InvariantCulture);
      DateTime reqDate;

      int intDepartmentId;
      if (!string.IsNullOrEmpty(ReqMonthYear))
      {

        intDepartmentId = int.Parse(DepartmentId);
        //user.DepartmentId;//User.Identity.GetUserId();//
        reqDate = DateTime.ParseExact(ReqMonthYear, "MM-yyyy",
                                 System.Globalization.CultureInfo.CurrentCulture);

      }
      else
      {
        //in case of empty parameters or First Time

        reqDate = DateTime.Now;
        string userId = User.Identity.GetUserId();
        intDepartmentId = dbLeaveOn.AspNetUsers.FirstOrDefault(x => x.Id == userId).DepartmentId;
        List<string> SelectedDeps = new List<string>();
        SelectedDeps.Add(intDepartmentId.ToString());
        ViewBag.SelectedDepartments = SelectedDeps;
        ViewBag.Departments = new SelectList(dbLeaveOn.Departments, "Id", "Name");

      }
      IQueryable<UD_TB_AccessTime_Data> depData = null;
      if (!string.IsNullOrEmpty(ReqMonthYear))
      {
        var identity = (ClaimsIdentity)User.Identity;
        IEnumerable<Claim> claims = identity.Claims;
        Claim claim = claims.Where(x => x.Value == DepartmentId).FirstOrDefault();

        if (claim is null) return null;


        reqDate = reqDate.AddYears(-1);
        //string userId = User.Identity.GetUserId();

        //int bioStarEmpNum = dbLeaveOn.AspNetUsers.FirstOrDefault(x => x.Id == userId).BioStarEmpNum.Value;
      
        //IQueryable<UD_TB_AccessTime_Data> allUsersData = null;
        List<AspNetUser> users = dbLeaveOn.AspNetUsers.Where(x => x.DepartmentId == intDepartmentId).ToList<AspNetUser>();

        List<int> userIds = users.Select(x => x.BioStarEmpNum.Value).ToList<int>();
        //foreach (AspNetUser user in users)
        //{

          depData = dbBioStar.UD_TB_AccessTime_Data.Where(x => userIds.Contains(x.EmployeeNumber.Value) && ((x.Date_IN.Value.Month == reqDate.Month && x.Date_IN.Value.Year == reqDate.Year) ||
                                                                                     x.Date_OUT.Value.Month == reqDate.Month && x.Date_OUT.Value.Year == reqDate.Year)).AsQueryable<UD_TB_AccessTime_Data>();

        //}
      }
      //return View(await db.UD_TB_AccessTime_Data.ToListAsync());
      if (string.IsNullOrEmpty(ReqMonthYear))
      {
        //in case of null param or first time
        if (!(depData is null))
        {
          return View(await depData.OrderBy(i => i.Date_IN).ToListAsync());
        }
        else
        {
          return View();
        }

      }
      else
      {
        return PartialView("_DepartmentData", await depData.OrderBy(i => i.Date_IN).ToListAsync());
      }

    }

  
    protected override void Dispose(bool disposing)
    {
      if (disposing)
      {
        dbBioStar.Dispose();
      }
      base.Dispose(disposing);
    }
  }
}

LeaveON/Views/AccessTimeData/DepartmentData.cshtml
@model IEnumerable<TimeManagement.Models.UD_TB_AccessTime_Data>

@{
  ViewBag.Title = "Index";
  Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>Index</h2>

  <p>
    @Html.ActionLink("Create New", "Create")
  </p>*@
@Html.DropDownList("DepartmentList", new MultiSelectList(ViewBag.Departments, "Value", "Text", ViewBag.SelectedDepartments), htmlAttributes: new { @class = "selectpicker", @id = "listDepartments", data_live_search = "true", data_actions_box = "true", data_done_button = "true" })
<select class="selectpicker" id="selectMonth" data-live-search="false" data-done-button="true">
  <option value="07-2020">July 2020</option>
  <option value="08-2020">August 2020</option>
  <option value="09-2020">September 2020</option>
  <option value="10-2020">October 2020</option>
  <option value="11-2020">November 2020</option>
  <option value="12-2020">December 2020</option>
  <option value="01-2021">January 2021</option>
  <option value="02-2021">February 2021</option>
  <option value="03-2021">March 2021</option>
  <option value="04-2021">April 2021</option>
  <option value="05-2021">May 2021</option>
  <option value="06-2021">June 2021</option>
</select>
<button id="load">go</button>
@{Html.RenderPartial("_DepartmentData", Model); }

<script type="text/javascript">

        $(document).ready(function () {

          $('#load').click(function () {
            var ReqMonthYear = $('#selectMonth').val();
            var DepartmentId = $('#listDepartments').val();
            
             $.ajax({
                    url: "@Url.Action("DepartmentData","AccessTimeData")",
                    data: { 'ReqMonthYear': ReqMonthYear, 'DepartmentId': DepartmentId },
                    type: "GET",
                    cache: false,
                    success: function (data) {
                        //alert(data);
                        $("#NewData").html(data);

                        //$("#hdnOrigComments").val($('#txtComments').val());
                        //$('#lblCommentsNotification').text(savingStatus);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        //$('#lblCommentsNotification').text("Error encountered while saving the comments.");
                        alert('Data provided was not valid');
                    }
             });
          });
        });


</script>

LeaveON/Views/AccessTimeData/PersonalData.cshtml
@model IEnumerable<TimeManagement.Models.UD_TB_AccessTime_Data>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>Index</h2>

  <p>
    @Html.ActionLink("Create New", "Create")
  </p>*@
<select class="selectpicker" id="selectMonth" data-live-search="false" data-done-button="true">
  <option value="07-2020">July 2020</option>
  <option value="08-2020">August 2020</option>
  <option value="09-2020">September 2020</option>
  <option value="10-2020">October 2020</option>
  <option value="11-2020">November 2020</option>
  <option value="12-2020">December 2020</option>
  <option value="01-2021">January 2021</option>
  <option value="02-2021">February 2021</option>
  <option value="03-2021">March 2021</option>
  <option value="04-2021">April 2021</option>
  <option value="05-2021">May 2021</option>
  <option value="06-2021">June 2021</option>
</select>
@{Html.RenderPartial("_PersonalData", Model); }

<script type="text/javascript">

        $(document).ready(function () {

          $('#selectMonth').change(function(){
            var ReqMonthYear = $(this).val();

             $.ajax({
                    url: "@Url.Action("PersonalData","AccessTimeData")",
                    data: { 'ReqMonthYear': ReqMonthYear },
                    type: "GET",
                    cache: false,
                    success: function (data) {
                        //alert(data);
                        $("#NewData").html(data);

                        //$("#hdnOrigComments").val($('#txtComments').val());
                        //$('#lblCommentsNotification').text(savingStatus);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        //$('#lblCommentsNotification').text("Error encountered while saving the comments.");
                        alert('Data provided was not valid');
                    }
             });
          });
        });


</script>

LeaveON/Views/AccessTimeData/_DepartmentData.cshtml
@model IEnumerable<TimeManagement.Models.UD_TB_AccessTime_Data>
  <div id="NewData">
    @if (!(Model is null))
    { 
    <table class="table">
      <tr>
        <th>
          @Html.DisplayNameFor(model => model.EmployeeName)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.EmployeeNumber)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.DepartmentID)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.DepartmentName)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.Date_IN)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.Day_IN)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.Time_IN)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.ReaderID_IN)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.DeviceName_IN)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.Date_OUT)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.Day_OUT)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.Time_OUT)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.ReaderID_OUT)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.DeviceName_OUT)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.Duration)
        </th>
        @*
        <th></th>*@
      </tr>

      @foreach (var item in Model)
      {
      <tr>
        <td>
          @Html.DisplayFor(modelItem => item.EmployeeName)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.EmployeeNumber)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.DepartmentID)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.DepartmentName)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Date_IN)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Day_IN)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Time_IN)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.ReaderID_IN)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.DeviceName_IN)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Date_OUT)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Day_OUT)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Time_OUT)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.ReaderID_OUT)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.DeviceName_OUT)
        </td>
        <td>

          @{
          int val = (int)item.Duration;
          TimeSpan minutes = TimeSpan.FromMinutes(val);

          @*<text>@minutes.ToString("hh':'mm':'ss")</text>*@
          <text>@minutes.ToString("hh':'mm")</text>
          }

          @*@Html.DisplayFor(modelItem => item.Duration/60)*@
        </td>
        @*
        <td>
          @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
          @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
          @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>*@
      </tr>
      }

    </table>
    }
  </div>

LeaveON/Views/AccessTimeData/_PersonalData.cshtml
@model IEnumerable<TimeManagement.Models.UD_TB_AccessTime_Data>
<div id="NewData">

  <table class="table">
    <tr>
      <th>
        @Html.DisplayNameFor(model => model.EmployeeName)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.EmployeeNumber)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.DepartmentID)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.DepartmentName)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.Date_IN)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.Day_IN)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.Time_IN)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.ReaderID_IN)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.DeviceName_IN)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.Date_OUT)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.Day_OUT)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.Time_OUT)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.ReaderID_OUT)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.DeviceName_OUT)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.Duration)
      </th>
      @*<th></th>*@
    </tr>

    @foreach (var item in Model)
    {
      <tr>
        <td>
          @Html.DisplayFor(modelItem => item.EmployeeName)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.EmployeeNumber)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.DepartmentID)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.DepartmentName)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Date_IN)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Day_IN)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Time_IN)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.ReaderID_IN)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.DeviceName_IN)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Date_OUT)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Day_OUT)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Time_OUT)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.ReaderID_OUT)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.DeviceName_OUT)
        </td>
        <td>

          @{
            int val = (int)item.Duration;
            TimeSpan minutes = TimeSpan.FromMinutes(val);

            @*<text>@minutes.ToString("hh':'mm':'ss")</text>*@
            <text>@minutes.ToString("hh':'mm")</text>
          }

          @*@Html.DisplayFor(modelItem => item.Duration/60)*@
        </td>
        @*<td>
              @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
              @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
              @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
          </td>*@
      </tr>
    }

  </table>

</div>